//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.20 at 05:59:54 PM CET 
//


package it.polito.dp2.RNS.sol3.service.jaxb.rnssystem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentifiedEntityRestricted complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifiedEntityRestricted">
 *   &lt;complexContent>
 *     &lt;restriction base="{}IdentifiedEntity">
 *       &lt;attribute name="id" use="required" type="{}StringPlateID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifiedEntityRestricted")
@XmlSeeAlso({
    Vehicle.class
})
public class IdentifiedEntityRestricted
    extends IdentifiedEntity
{


}
