//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.20 at 05:59:54 PM CET 
//


package it.polito.dp2.RNS.sol3.service.jaxb.rnssystem;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol3.service.jaxb.rnssystem package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol3.service.jaxb.rnssystem
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VehiclePosition }
     * 
     */
    public VehiclePosition createVehiclePosition() {
        return new VehiclePosition();
    }

    /**
     * Create an instance of {@link Places }
     * 
     */
    public Places createPlaces() {
        return new Places();
    }

    /**
     * Create an instance of {@link Webplace }
     * 
     */
    public Webplace createWebplace() {
        return new Webplace();
    }

    /**
     * Create an instance of {@link Gate }
     * 
     */
    public Gate createGate() {
        return new Gate();
    }

    /**
     * Create an instance of {@link RoadSegment }
     * 
     */
    public RoadSegment createRoadSegment() {
        return new RoadSegment();
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link Webvehicle }
     * 
     */
    public Webvehicle createWebvehicle() {
        return new Webvehicle();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link VehiclePath }
     * 
     */
    public VehiclePath createVehiclePath() {
        return new VehiclePath();
    }

    /**
     * Create an instance of {@link Rns }
     * 
     */
    public Rns createRns() {
        return new Rns();
    }

    /**
     * Create an instance of {@link Road }
     * 
     */
    public Road createRoad() {
        return new Road();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link VehicleTrack }
     * 
     */
    public VehicleTrack createVehicleTrack() {
        return new VehicleTrack();
    }

    /**
     * Create an instance of {@link VehState }
     * 
     */
    public VehState createVehState() {
        return new VehState();
    }

    /**
     * Create an instance of {@link Vehicles }
     * 
     */
    public Vehicles createVehicles() {
        return new Vehicles();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Webrns }
     * 
     */
    public Webrns createWebrns() {
        return new Webrns();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link IdentifiedEntityRestricted }
     * 
     */
    public IdentifiedEntityRestricted createIdentifiedEntityRestricted() {
        return new IdentifiedEntityRestricted();
    }

    /**
     * Create an instance of {@link IdentifiedEntity }
     * 
     */
    public IdentifiedEntity createIdentifiedEntity() {
        return new IdentifiedEntity();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

}
