//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.20 at 05:59:54 PM CET 
//


package it.polito.dp2.RNS.sol3.service.jaxb.rnssystem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;choice>
 *           &lt;element name="gate" type="{}Gate"/>
 *           &lt;element name="roadSegment" type="{}RoadSegment"/>
 *           &lt;element name="parkingArea" type="{}ParkingArea"/>
 *         &lt;/choice>
 *         &lt;element name="vehicles" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "self",
    "gate",
    "roadSegment",
    "parkingArea",
    "vehicles"
})
@XmlRootElement(name = "webplace")
public class Webplace {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String self;
    protected Gate gate;
    protected RoadSegment roadSegment;
    protected ParkingArea parkingArea;
    @XmlSchemaType(name = "anyURI")
    protected String vehicles;

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link Gate }
     *     
     */
    public Gate getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gate }
     *     
     */
    public void setGate(Gate value) {
        this.gate = value;
    }

    /**
     * Gets the value of the roadSegment property.
     * 
     * @return
     *     possible object is
     *     {@link RoadSegment }
     *     
     */
    public RoadSegment getRoadSegment() {
        return roadSegment;
    }

    /**
     * Sets the value of the roadSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadSegment }
     *     
     */
    public void setRoadSegment(RoadSegment value) {
        this.roadSegment = value;
    }

    /**
     * Gets the value of the parkingArea property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingArea }
     *     
     */
    public ParkingArea getParkingArea() {
        return parkingArea;
    }

    /**
     * Sets the value of the parkingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingArea }
     *     
     */
    public void setParkingArea(ParkingArea value) {
        this.parkingArea = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicles(String value) {
        this.vehicles = value;
    }

}
